name: pbdl
description: A starting point for Dart libraries or applications.
version: 2.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  json_annotation: ^4.8.1
  hex: ^0.2.0
  quick_log: ^5.5.3
  http2: ^2.0.0
  path: ^1.9.0
  azblob: ^3.0.1
  recase: ^4.1.0
  archive: ^3.3.2
  meta: ^1.12.0
  uuid: ^4.2.1
  get_it: ^7.6.4

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0   # pedantic 대신
  test: ^1.24.0
